#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
#include "images/startScreen.h"
//#include "images/playScreen.h"
#include "images/raid.h"
#include "images/roach.h"
#include "images/winScreen.h"
#include "images/loseScreen.h"

/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  STARTPIC,
  STARTWORD,
  PLAYINIT,
  PLAY,
  WIN,
  LOSE,
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = STARTPIC;
  int sec;
  while (1) {
    currentButtons = BUTTONS; 
    // Load the current state of the buttons
    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    switch (state) {
      case STARTPIC:
          waitForVBlank();
          drawFullScreenImageDMA(startScreen);
          state = STARTWORD;
        break;

      case STARTWORD:
            waitForVBlank();
            drawString(130, 10, "Press enter to start", BLACK);
  
          if (KEY_DOWN(BUTTON_START, currentButtons)) {
          state = PLAYINIT;
          }
        break;
      
      case PLAYINIT:
        waitForVBlank();
        fillScreenDMA(GRAY);
        sec = 15;
        raidObj.r = 65;
        raidObj.c = 100;
        roachObj.r = (rand() % 134);
        roachObj.c = (rand() % 217);
        waitForVBlank();
        drawImageDMA(roachObj.r, roachObj.c, 23, 16, roach);
        waitForVBlank();
        drawImageDMA(raidObj.r, raidObj.c, 9, 23, raid);
        state = PLAY;
        break;
      
      case PLAY:
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
          state = STARTPIC;
        }
        waitForVBlank();
        
        drawRectDMA(roachObj.r, roachObj.c, 23, 16, GRAY);
        drawRectDMA(raidObj.r, raidObj.c, 9, 23, GRAY);

        if (KEY_DOWN(BUTTON_LEFT, currentButtons)) {
          if (raidObj.c > 1) {
            raidObj.c -= 2;
          }
        } else if (KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
          if (raidObj.c < 231) {
            raidObj.c += 2;
          }
        } else if (KEY_DOWN(BUTTON_UP, currentButtons)) {
          if (raidObj.r > 1) {
            raidObj.r -= 2;
          }
        } else if (KEY_DOWN(BUTTON_DOWN, currentButtons)) {
          if (raidObj.r < 126) {
            raidObj.r += 2;
          }
        }
        
        drawImageDMA(roachObj.r, roachObj.c, 23, 16, roach);
        drawImageDMA(raidObj.r, raidObj.c, 9, 23, raid);

        if (vBlankCounter % 75 == 0) {
          drawRectDMA(roachObj.r, roachObj.c, 23, 16, GRAY);
          do {
            roachObj.r = (rand() % 134);
            roachObj.c = (rand() % 217);
          } while (abs((roachObj.c + 12) - (raidObj.c + 5)) <= 10  && abs((roachObj.r + 8) - (raidObj.r + 11)) <= 10);
            drawImageDMA(roachObj.r, roachObj.c, 23, 16, roach);
        }

        if (vBlankCounter % 60 == 0) {
          drawRectDMA(150, 0, 240, 10, BLACK);
          sec--;
          char str[30];
          sprintf(str, "Time Left: %d", sec);
          drawString(150, 5, str, WHITE);
        }
        if (abs((roachObj.c + 12) - (raidObj.c + 5)) <= 10  && abs((roachObj.r + 8) - (raidObj.r + 11)) <= 10) {
          waitForVBlank();
          drawFullScreenImageDMA(winScreen);
          state = WIN;
        } else if (sec == 0) {
          waitForVBlank();
          drawFullScreenImageDMA(loseScreen);
          state = LOSE;
        }
        break;
      case WIN:
        
        // state = ?
        waitForVBlank();
        char str[30];
        sprintf(str, "Time Left: %d sec.", sec);
        drawString(60, 120, str, GRAY);
        drawString(75, 120, "YAY, YOU WON! :)", GRAY);
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
          state = STARTPIC;
        }
        break;
        
      case LOSE:
        // state = ?
        waitForVBlank();
        drawString(80, 7, ":( Try again?", WHITE);
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
          state = STARTPIC;
        }
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
